import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { describe, expect, test } from 'vitest'

const read = (name: string): string => readFileSync(fileURLToPath(new URL(name, import.meta.url)), 'utf8')

describe('Tasks 视图源守卫', () => {
  test('键盘与可达性:表单原生提交、Esc 取消、行内按钮 aria-label、列表 role', () => {
    const source = read('TasksView.tsx')
    expect(source).toContain('onSubmit={submitDraft}')
    expect(source).toContain("key === 'Escape'")
    expect(source).toContain('aria-label')
    expect(source).toContain('role="list"')
    expect(source).toContain('data-priority')
    expect(source).not.toContain('window.prompt')
    expect(source).not.toContain('globalThis.prompt')
    expect(source).toContain('onSubmit={submitRename}')
    expect(source).toContain('onSubmit={submitViewDraft}')
    expect(source).toContain('matchesTaskView')
    expect(source).toContain('tasks-view-checks')
    expect(source).toContain('aria-labelledby="tasks-view-dialog-title"')
    expect(source).toContain('role="dialog"')
    expect(source).toContain('aria-modal="true"')
    expect(source).toContain('tasks-dialog-backdrop')
    expect(source).toContain('tasks-new-project-form')
    expect(source).toContain('remindChoiceFromTask')
    expect(source).toContain('RECURRENCE_LABELS')
  })
  test('样式:使用全局 token、窄屏断点与减少动画', () => {
    const css = read('Tasks.css')
    for (const token of ['--bg-secondary', '--text-primary', '--border', '--accent', '--focus-ring']) {
      expect(css).toContain(`var(${token}`)
    }
    expect(css).toContain('max-width:')
    expect(css).toContain('prefers-reduced-motion')
  })
  test('导航注册 tasks 页', () => {
    const nav = read('../Workspace/WorkspaceNav.tsx')
    expect(nav).toContain("'tasks'")
    expect(nav).toContain('任务')
  })
  test('看板:模式切换、分组选择、拖拽与卡片可达性', () => {
    const view = read('TasksView.tsx')
    expect(view).toContain("from './TasksBoard'")
    expect(view).toContain('tasks-tabs')
    expect(view).toContain('tasks-tab')
    expect(view).toContain('aria-pressed')
    expect(view).toContain('看板分组方式')
    expect(view).toContain('tasks.update(id, patch)')
    const board = read('TasksBoard.tsx')
    expect(board).toContain('draggable')
    expect(board).toContain("setData('text/plain'")
    expect(board).toContain('onDrop')
    expect(board).toContain('tasks-board-column')
    expect(board).toContain('role="list"')
    expect(board).toContain('aria-label')
    expect(board).toContain('preventDefault')
    expect(board).toContain('tasks-board-card-dot')
    expect(board).toContain('tasks-board-card-chips')
    const css = read('Tasks.css')
    expect(css).toContain('.tasks-tab[aria-pressed=')
    expect(css).toContain('.tasks-board-card-dot')
  })
  test('字段管理:弹窗可达性、表单集成与列表 chip', () => {
    const dialog = read('TaskFieldsDialog.tsx')
    expect(dialog).toContain('role="dialog"')
    expect(dialog).toContain('aria-modal="true"')
    expect(dialog).toContain('tasks-field-dialog-title')
    expect(dialog).not.toContain('window.prompt')
    expect(dialog).toContain('onSubmit')
    const view = read('TasksView.tsx')
    expect(view).toContain("from './TaskFieldsDialog'")
    expect(view).toContain('任务 ${field.name}')
    const css = read('Tasks.css')
    expect(css).toContain('.tasks-board {')
    expect(css).toContain('.tasks-field-row')
  })
})
