import type { BrowserWindow } from 'electron'
import { mkdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { waitForRenderer } from './storage-smoke'

export async function runTaskEditUISmoke(window: BrowserWindow): Promise<void> {
  const run = (source: string) => window.webContents.executeJavaScript(source)
  const click = (selector: string) => run(`document.querySelector(${JSON.stringify(selector)}).click()`)
  const fill = (selector: string, value: string) => run(`(() => { const e=document.querySelector(${JSON.stringify(selector)}); Object.getOwnPropertyDescriptor(e.tagName==='SELECT'?HTMLSelectElement.prototype:HTMLInputElement.prototype,'value').set.call(e,${JSON.stringify(value)});e.dispatchEvent(new Event('input',{bubbles:true}));e.dispatchEvent(new Event('change',{bubbles:true})); })()`)
  const wait = (condition: string) => waitForRenderer(window, condition)
  const chooseDateTime = async (label: string, value: string) => {
    await click(`[aria-label="${label}"]`)
    await wait("!!document.querySelector('.app-datetime-dialog[open]')")
    await fill(`[aria-label="${label}日期"]`, value.slice(0, 10))
    await click('[aria-label=选择时分]')
    await click(`.app-time-column[aria-label="小时"] [data-value="${value.slice(11, 13)}"]`)
    await click(`.app-time-column[aria-label="分钟"] [data-value="${value.slice(14, 16)}"]`)
    await click('.app-datetime-dialog button[type=submit]')
    await wait("!document.querySelector('.app-datetime-dialog')")
  }
  const assert = async (condition: string) => { if (!await run(condition)) throw new Error(`Task edit assertion: ${condition}`) }
  window.webContents.send('open-chat-panel')
  await wait("!!document.querySelector('.chat-panel')")
  if (!await run("!!document.querySelector('[data-workspace-nav=tasks]')")) {
    await click('[aria-label="窗口模式"]'); await click('[data-workspace-mode-option=workspace]')
  }
  await click('[data-workspace-nav=tasks]')
  await wait("!!document.querySelector('.tasks-create')")
  const task = await run(`window.electronAPI.tasks.create({title:'编辑体验验收',note:'保留备注',priority:'medium',dueAt:new Date(2030,0,31,9).getTime(),recurrence:'monthly',reminderTimes:[new Date(2030,0,31,8).getTime()],checklist:[{id:'step',title:'保留子项',done:false}]})`)
  const openEditor = async () => {
    await run(`window.dispatchEvent(new CustomEvent('chouyu:task-navigation',{detail:{taskId:${JSON.stringify(task.id)}}}))`)
    await wait("document.querySelector('[aria-label=任务标题]')?.value==='编辑体验验收'")
    await run('new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)))')
  }
  await openEditor()
  // A pristine editor closes directly; edited content survives cancelled discard.
  await click('[aria-label="关闭任务弹窗"]')
  await wait("!document.querySelector('.tasks-composer')")
  await openEditor()
  await fill('[aria-label="任务标题"]', '尚未保存')
  await run("document.querySelector('[aria-label=任务标题]').dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true,cancelable:true}))")
  await wait("!!document.querySelector('.app-confirm-dialog[open]')")
  await click('.app-confirm-dialog button:first-child')
  await assert("document.querySelector('[aria-label=任务标题]').value==='尚未保存'")
  await click('[aria-label="关闭任务弹窗"]')
  await wait("!!document.querySelector('.app-confirm-dialog[open]')")
  await click('.app-confirm-dialog .app-button-danger')
  await wait("!document.querySelector('.tasks-composer')")
  await assert(`window.electronAPI.tasks.get('${task.id}').then(t=>t.title==='编辑体验验收')`)
  await click('[data-view-selection=all]')
  await click('.tasks-tabs button:first-child')
  const card = `[data-task-id="${task.id}"]`
  await wait(`!!document.querySelector('${card} .task-card-priority')`)
  await click(`${card} .task-card-checklist-toggle`)
  await wait(`!!document.querySelector('${card} .task-card-checklist-row input')`)
  await assert("!document.querySelector('.tasks-composer')")
  await click(`${card} .task-card-checklist-row`)
  await wait(`document.querySelector('${card} .task-card-checklist-row input')?.checked===true`)
  await assert(`window.electronAPI.tasks.get('${task.id}').then(t=>t.status==='open'&&t.checklist[0].done&&t.note==='保留备注'&&t.reminders[0].at===${task.reminders[0].at})`)
  await assert(`document.querySelector('${card} .task-card-checklist-toggle').getAttribute('aria-expanded')==='true'`)
  await click(`${card} .task-card-checklist-toggle`)
  await assert(`!document.querySelector('${card} .task-card-checklist-row')`)
  await click(`${card} .task-card-priority`)
  await wait("!!document.querySelector('.tasks-field-editor[open]')")
  await assert("!document.querySelector('.tasks-composer')")
  await fill('[aria-label="卡片优先级"]', 'high')
  await click('.tasks-field-editor button[type=submit]')
  await wait("!document.querySelector('.tasks-field-editor')")
  await assert(`window.electronAPI.tasks.get('${task.id}').then(t=>t.priority==='high'&&t.note==='保留备注'&&t.checklist[0].title==='保留子项'&&t.reminders[0].at===${task.reminders[0].at})`)
  // Board uses the same field editor and preserves recurrence/reminder offsets.
  await click('.tasks-tabs button:nth-child(2)')
  await wait(`!!document.querySelector('.tasks-board-card${card} .task-card-due')`)
  await click(`${card} .task-card-checklist-toggle`)
  await wait(`!!document.querySelector('${card} .task-card-checklist-row input')`)
  await assert(`document.querySelector('${card} .task-card-checklist-row input').checked===true`)
  await run(`(() => { const input=document.querySelector('${card} .task-card-checklist-row input'); input.focus(); })()`)
  window.webContents.sendInputEvent({ type: 'keyDown', keyCode: 'Space' })
  window.webContents.sendInputEvent({ type: 'keyUp', keyCode: 'Space' })
  await wait(`document.querySelector('${card} .task-card-checklist-row input')?.checked===false`)
  await assert("!document.querySelector('.tasks-composer')")
  // A rejected write keeps the checkbox unchanged and offers retry.
  await run(`(async () => { const t=await window.electronAPI.tasks.get('${task.id}'); await window.electronAPI.tasks.update(t.id,{checklist:[...t.checklist,{id:'failure',title:'失败重试',done:false}]}); })()`)
  await wait(`document.querySelectorAll('${card} .task-card-checklist-row').length===2`)
  await run(`(async () => { const t=await window.electronAPI.tasks.get('${task.id}'); const writing=window.electronAPI.tasks.update(t.id,{checklist:t.checklist.filter(i=>i.id!=='failure')}); document.querySelectorAll('${card} .task-card-checklist-row input')[1].click(); await writing; })()`)
  await wait(`document.querySelector('${card} .task-card-checklist [role=alert]')?.textContent.includes('保存失败')`)
  await click(`${card} .task-card-checklist-row input`)
  await wait(`document.querySelector('${card} .task-card-checklist-row input')?.checked===true`)
  await assert(`!document.querySelector('${card} .task-card-checklist [role=alert]')`)
  if (process.env.CHOUYU_TASK_GROUP_ARTIFACTS) {
    const directory = process.env.CHOUYU_TASK_GROUP_ARTIFACTS
    mkdirSync(directory, { recursive: true })
    for (const mode of ['list', 'board']) {
      await click(`.tasks-tabs button:nth-child(${mode === 'list' ? 1 : 2})`)
      await wait(`!!document.querySelector('${card} .task-card-checklist-toggle')`)
      if (!await run(`document.querySelector('${card} .task-card-checklist-toggle').getAttribute('aria-expanded')==='true'`)) await click(`${card} .task-card-checklist-toggle`)
      for (const theme of ['light', 'dark']) {
        await run(`document.documentElement.dataset.theme='${theme}'; document.querySelector('${card} .task-card-checklist').scrollIntoView({block:'center'})`)
        await run('new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve)))')
        await window.webContents.capturePage(undefined, { stayHidden: true, stayAwake: true })
        writeFileSync(join(directory, `task-checklist-${mode}-${theme}.png`), (await window.webContents.capturePage(undefined, { stayHidden: true, stayAwake: true })).toPNG())
      }
    }
  }
  await click(`.tasks-board-card${card} .task-card-due`)
  await chooseDateTime('卡片截止时间', '2030-02-28T09:00')
  const directory = process.env.CHOUYU_TASK_GROUP_ARTIFACTS
  if (directory) {
    mkdirSync(directory, { recursive: true })
    for (const theme of ['light', 'dark']) {
      await run(`document.documentElement.dataset.theme='${theme}'`)
      await run('new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve)))')
      await window.webContents.capturePage(undefined, { stayHidden: true, stayAwake: true })
      writeFileSync(join(directory, `task-field-${theme}.png`), (await window.webContents.capturePage(undefined, { stayHidden: true, stayAwake: true })).toPNG())
    }
  }
  await click('.tasks-field-editor button[type=submit]')
  await wait("!document.querySelector('.tasks-field-editor')")
  await assert(`window.electronAPI.tasks.get('${task.id}').then(t=>t.dueAt===new Date(2030,1,28,9).getTime()&&t.reminders[0].at===t.dueAt-3600000&&t.recurrence==='monthly')`)
  // A storage/validation failure leaves the edited value available for retry.
  await click(`${card} .task-card-due`)
  await chooseDateTime('卡片截止时间', '2030-03-28T09:00')
  await run(`window.electronAPI.tasks.update('${task.id}',{note:'外部更新'})`)
  await click('.tasks-field-editor button[type=submit]')
  await wait("document.querySelector('.tasks-field-editor [role=alert]')?.textContent.includes('任务已发生变化')")
  await assert("document.querySelector('[aria-label=卡片截止时间]').dataset.value==='2030-03-28T09:00'")
  await click('.tasks-field-editor .tasks-form-actions button:first-child')
  await run("Array.from(document.querySelectorAll('.tasks-field-editor button')).find(b=>b.textContent==='放弃修改').click()")
  await wait("!document.querySelector('.tasks-field-editor')")
  // Checklist creation stays in a modal and sorting preserves each item's identity.
  await openEditor()
  await click('.tasks-checklist-collapse')
  await assert("document.querySelector('#tasks-editor-checklist').hidden && document.querySelector('[aria-label=新增子项]').textContent===''")
  await click('.tasks-checklist-collapse')
  await assert("!document.querySelector('#tasks-editor-checklist').hidden")
  await click('[aria-label="新增子项"]')
  await wait("!!document.querySelector('.tasks-subitem-dialog[open]')")
  await fill('[aria-label="新子项名称"]', '取消的子项')
  window.webContents.sendInputEvent({ type: 'keyDown', keyCode: 'Escape' })
  window.webContents.sendInputEvent({ type: 'keyUp', keyCode: 'Escape' })
  await wait("!document.querySelector('.tasks-subitem-dialog')")
  await assert("!!document.querySelector('.tasks-composer') && document.querySelectorAll('.tasks-checklist-row').length===1")
  await click('[aria-label="新增子项"]')
  await wait("!!document.querySelector('.tasks-subitem-dialog[open]')")
  await fill('[aria-label="新子项名称"]', '新步骤')
  await click('[aria-label="新子项截止时间"]')
  await wait("!!document.querySelector('.app-datetime-dialog[open]')")
  await fill('[aria-label="新子项截止时间日期"]', '2030-01-01')
  await run("document.querySelector('[aria-label=新子项截止时间日期]').focus(); new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)))")
  window.webContents.sendInputEvent({ type: 'keyDown', keyCode: 'Escape' })
  window.webContents.sendInputEvent({ type: 'keyUp', keyCode: 'Escape' })
  await wait("!document.querySelector('.app-datetime-dialog')")
  await assert("document.querySelector('[aria-label=新子项截止时间]').dataset.value==='' && !!document.querySelector('.tasks-subitem-dialog[open]')")
  await click('[aria-label="新子项截止时间"]')
  await wait("!!document.querySelector('.app-datetime-dialog[open]')")
  await fill('[aria-label="新子项截止时间日期"]', '2030-02-31')
  await click('.app-datetime-dialog button[type=submit]')
  await wait("document.querySelector('.app-datetime-dialog [role=alert]')?.textContent.includes('有效日期')")
  await assert("document.querySelector('[aria-label=新子项截止时间]').dataset.value===''")
  await fill('[aria-label="新子项截止时间日期"]', '2030-04-01')
  const calendarBounds = await run("['.app-datetime-dialog', '.app-datetime-inputs', '.app-datetime-dialog footer'].map(s=>{const r=document.querySelector(s).getBoundingClientRect();return [r.x,r.y,r.width,r.height]})")
  await click('[aria-label=选择时分]')
  await assert(`${JSON.stringify(calendarBounds)}.every((bounds,i)=>bounds.every((n,j)=>Math.abs(n-['.app-datetime-dialog', '.app-datetime-inputs', '.app-datetime-dialog footer'].map(s=>{const r=document.querySelector(s).getBoundingClientRect();return [r.x,r.y,r.width,r.height]})[i][j])<1))`)
  await click('.app-time-column[aria-label=小时] [data-value="10"]')
  await click('.app-time-presets [aria-label="45分"]')
  await assert("document.querySelector('.app-time-toggle strong').textContent==='10:45' && document.querySelector('.app-time-column[aria-label=分钟] [aria-selected=true]').dataset.value==='45'")
  await run("document.querySelector('.app-time-column[aria-label=分钟] [aria-selected=true]').focus()")
  window.webContents.sendInputEvent({ type: 'keyDown', keyCode: 'Down' })
  window.webContents.sendInputEvent({ type: 'keyUp', keyCode: 'Down' })
  await wait("document.querySelector('.app-time-toggle strong').textContent==='10:46'")
  await assert("Array.from(document.querySelectorAll('.app-time-presets button')).every(b=>b.getAttribute('aria-pressed')==='false')")
  await click('.app-time-heading button')
  await assert("!!document.querySelector('.rdp-root') && document.activeElement===document.querySelector('.app-time-toggle') && document.querySelector('.app-datetime-inputs input').value==='2030-04-01'")
  await click('[aria-label=选择时分]')
  await assert("document.querySelector('.app-time-toggle strong').textContent==='10:46'")
  await click('.app-time-presets [aria-label="15分"]')
  if (directory) {
    await run('new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)))')
    await window.webContents.capturePage(undefined,{stayHidden:true,stayAwake:true})
    writeFileSync(join(directory,'task-subitem-calendar.png'),(await window.webContents.capturePage(undefined,{stayHidden:true,stayAwake:true})).toPNG())
    const theme = await run('document.documentElement.dataset.theme')
    try {
      for (const mode of ['light','dark']) for (const width of [1100,375]) {
        await run(`document.documentElement.dataset.theme='${mode}'`)
        window.webContents.enableDeviceEmulation({screenPosition:'desktop',screenSize:{width,height:700},viewPosition:{x:0,y:0},deviceScaleFactor:1,viewSize:{width,height:700},scale:1})
        await run('new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)))')
        await assert("(() => {const p=document.querySelector('.app-datetime-dialog'),r=p.getBoundingClientRect();return r.left>=0 && r.right<=innerWidth+1 && r.top>=0 && r.bottom<=innerHeight+1 && p.scrollWidth<=p.clientWidth+1})()")
        const expandedBounds = await run("document.querySelector('.app-datetime-dialog').getBoundingClientRect().toJSON()")
        await window.webContents.capturePage(undefined,{stayHidden:true,stayAwake:true})
        writeFileSync(join(directory,`common-calendar-${mode}-${width}.png`),(await window.webContents.capturePage(undefined,{stayHidden:true,stayAwake:true})).toPNG())
        await click('[aria-label=选择时分]')
        await run('new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)))')
        await assert("document.querySelector('.app-datetime-dialog').getBoundingClientRect().height < 460")
        await assert(`Math.abs(document.querySelector('.app-datetime-dialog').getBoundingClientRect().y-${expandedBounds.y})<1 && Math.abs(document.querySelector('.app-datetime-dialog').getBoundingClientRect().height-${expandedBounds.height})<1`)
        await window.webContents.capturePage(undefined,{stayHidden:true,stayAwake:true})
        writeFileSync(join(directory,`common-calendar-compact-${mode}-${width}.png`),(await window.webContents.capturePage(undefined,{stayHidden:true,stayAwake:true})).toPNG())
        await click('[aria-label=选择时分]')
      }
    } finally { window.webContents.disableDeviceEmulation(); await run(`document.documentElement.dataset.theme=${JSON.stringify(theme)}`) }

  }
  await click('.app-datetime-dialog button[type=submit]')
  await wait("!document.querySelector('.app-datetime-dialog')")
  await assert("document.querySelector('[aria-label=新子项截止时间]').dataset.value==='2030-04-01T10:15'")
  if (directory) {
    await run('new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)))')
    writeFileSync(join(directory,'task-subitem-dialog.png'),(await window.webContents.capturePage(undefined,{stayHidden:true,stayAwake:true})).toPNG())
  }
  await click('.tasks-subitem-dialog button[type=submit]')
  await wait("document.querySelectorAll('.tasks-checklist-row').length===2")
  await run(`(() => {const rows=document.querySelectorAll('.tasks-checklist-row'),dt=new DataTransfer();rows[1].querySelector('.tasks-checklist-drag').dispatchEvent(new DragEvent('dragstart',{bubbles:true,dataTransfer:dt}));})()`)
  await run(`(() => {const row=document.querySelector('.tasks-checklist-row'),r=row.getBoundingClientRect();row.dispatchEvent(new DragEvent('drop',{bubbles:true,cancelable:true,clientY:r.top,dataTransfer:new DataTransfer()}));})()`)
  await assert("document.querySelector('.tasks-checklist-title').value==='新步骤'")
  if (directory) {
    await run('new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)))')
    writeFileSync(join(directory,'task-subitems-editor.png'),(await window.webContents.capturePage(undefined,{stayHidden:true,stayAwake:true})).toPNG())
  }
  await click('.tasks-composer > form button[type=submit]')
  await wait("!document.querySelector('.tasks-composer')")
  await assert(`window.electronAPI.tasks.get('${task.id}').then(t=>t.checklist[0].title==='新步骤'&&t.checklist[0].dueAt===new Date(2030,3,1,10,15).getTime()&&t.checklist[1].id==='step')`)
  await click('[aria-label="字段配置"]')
  await click('.tasks-checklist-default input')
  await wait(`document.querySelector('${card} .task-card-checklist-toggle')?.getAttribute('aria-expanded')==='true'`)
  await click('.tasks-tabs button:first-child')
  await wait(`document.querySelector('${card} .task-card-checklist-toggle')?.getAttribute('aria-expanded')==='true'`)
  await assert("JSON.parse(localStorage.getItem('chouyu:task-view-preferences:v1'))[localStorage.getItem('chouyu:task-selection')].expandChecklist===true")
  window.webContents.reload()
  await wait("!!document.querySelector('#root')")
  window.webContents.send('open-chat-panel')
  await wait("!!document.querySelector('[data-workspace-nav=tasks]')")
  await click('[data-workspace-nav=tasks]')
  await wait(`document.querySelector('${card} .task-card-checklist-toggle')?.getAttribute('aria-expanded')==='true'`)
  await openEditor()
  await assert("document.querySelector('[aria-label=任务开始时间]').textContent.includes('开始') && document.querySelector('[aria-label=任务开始时间]').textContent.includes('未设置') && document.querySelector('.tasks-schedule-range').textContent.includes('—')")
  await chooseDateTime('任务开始时间', '2030-02-27T09:00')
  await click('[aria-label="任务截止时间"]')
  await wait("!!document.querySelector('.app-datetime-dialog[open]')")
  await click('.app-datetime-dialog [aria-label="2030-02-28"]')
  await click('.app-datetime-dialog button[type=submit]')
  await wait("!document.querySelector('.app-datetime-dialog')")
  await assert("document.querySelector('[aria-label=任务开始时间]').dataset.value.startsWith('2030-02-27') && document.querySelector('[aria-label=任务截止时间]').dataset.value.startsWith('2030-02-28')")
  await assert("document.querySelector('[aria-label=任务开始时间]').textContent.includes('开始') && document.querySelector('[aria-label=任务截止时间]').textContent.includes('截止')")
  await assert("!!document.querySelector('[aria-label=设置任务提醒]') && !!document.querySelector('[aria-label=设置任务重复]') && !document.querySelector('.tasks-date-pages') && getComputedStyle(document.querySelector('.tasks-checklist-editor')).borderTopWidth==='0px'")
  if (directory) {
    await run('new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)))')
    await window.webContents.capturePage(undefined,{stayHidden:true,stayAwake:true})
    writeFileSync(join(directory,'task-date-range.png'),(await window.webContents.capturePage(undefined,{stayHidden:true,stayAwake:true})).toPNG())
  }
  await click('.tasks-composer > form button[type=submit]')
  await wait("!document.querySelector('.tasks-composer')")
  await assert(`window.electronAPI.tasks.get('${task.id}').then(t=>t.startAt!==null && t.startAt<t.dueAt && new Date(t.startAt).getDate()===27 && new Date(t.dueAt).getDate()===28)`)
  await run(`window.electronAPI.tasks.remove('${task.id}')`)
  console.log('CHOUYU_TASK_EDIT_UI_SMOKE_PASSED')
}
