import { afterEach, describe, expect, it } from 'vitest'
import { mkdtempSync, mkdirSync, writeFileSync, rmSync, readFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { SkillLibrary, inspectSkillDirectory } from './library'

const roots: string[] = []
afterEach(() => { for (const root of roots.splice(0)) rmSync(root, { recursive: true, force: true }) })
function fixture(text = '先给结论，再给依据。') {
  const root = mkdtempSync(join(tmpdir(), 'chouyu-skills-')); roots.push(root)
  const source = join(root, 'source'); mkdirSync(source)
  writeFileSync(join(source, 'SKILL.md'), `---\nname: careful-review\ndescription: 评审工作方法\n---\n${text}`)
  return { root, source, library: new SkillLibrary(join(root, 'data')) }
}
describe('contact skill library', () => {
  it('persists independent contact assignments and rejects stale writes', () => {
    const { root, source, library } = fixture()
    const skill = library.publish('careful-review', source)
    library.configure('alice', skill.id, 'enable', 0)
    expect(library.snapshot('alice').instruction).toContain('先给结论，再给依据。')
    expect(library.snapshot('bob').instruction).toBe('')
    expect(() => library.configure('alice', skill.id, 'disable', 0)).toThrow(/变化/)
    const reopened = new SkillLibrary(join(root, 'data'))
    expect(reopened.snapshot('alice').entries[0].id).toBe(skill.id)
    expect(reopened.list('bob').skills[0].enabled).toBe(false)
    reopened.configure('alice', skill.id, 'disable', 1)
    expect(reopened.snapshot('alice').instruction).toBe('')
    expect(reopened.list('alice').skills[0].assigned).toBe(true)
    expect(() => reopened.uninstall(skill.id)).toThrow(/联系人/)
    reopened.removeContact('alice')
    reopened.uninstall(skill.id)
    expect(reopened.list('bob').skills).toEqual([])
  })
  it('includes local reference text in the same immutable snapshot', () => {
    const { source, library } = fixture('使用 references/rules.md 的规则。')
    mkdirSync(join(source, 'references')); writeFileSync(join(source, 'references/rules.md'), '必须列举可验证的依据。')
    const skill = library.publish('@author/careful-review', source)
    library.configure('alice', skill.id, 'enable', 0)
    const snapshot = library.snapshot('alice')
    expect(snapshot.instruction).toContain('必须列举可验证的依据。')
    expect(snapshot.entries[0].digest).toMatch(/^[a-f0-9]{64}$/)
    library.configure('alice', skill.id, 'disable', 1)
    expect(snapshot.instruction).toContain('必须列举可验证的依据。')
  })
  it('enables instructions independently from scripts and keeps execution separately authorized', () => {
    const { source, library } = fixture('执行 scripts/run.py。')
    mkdirSync(join(source, 'scripts')); writeFileSync(join(source, 'scripts/run.py'), 'print("hello")')
    const skill = library.publish('script-skill', source)
    expect(skill.unavailableReason).toBeUndefined()
    expect(skill.compatibility?.scripts).toEqual([{ path: 'scripts/run.py', runtime: 'python' }])
    library.configure('alice', skill.id, 'enable', 0)
    expect(library.snapshot('alice').entries[0].scriptsEnabled).toBe(false)
    library.configure('alice', skill.id, 'enable_scripts', 1)
    expect(library.snapshot('alice').entries[0].scriptsEnabled).toBe(true)
    expect(library.snapshot('bob').entries).toEqual([])
  })
  it('rejects oversized instructions without truncating them', () => {
    const { source } = fixture('字'.repeat(40000))
    expect(() => inspectSkillDirectory(source)).toThrow(/过长/)
  })
  it('reports external dependencies without pretending they are available in instruction mode', () => {
    const { source, library } = fixture('Requires an active Salesforce account and a connected Salesforce MCP server. Use salesforce.query to retrieve records.')
    const skill = library.publish('crm', source)
    expect(skill.compatibility?.externalRequirements.join(' ')).toContain('Salesforce')
    library.configure('alice', skill.id, 'enable', 0)
    expect(library.snapshot('alice').instruction).toContain('未连接')
  })
  it('lets users disable and remove multiple broken skills without loading their contents', () => {
    const { root, source, library } = fixture()
    library.publish('one', source); library.publish('two', source)
    library.configure('alice', 'one', 'enable', 0); library.configure('alice', 'two', 'enable', 1)
    const state = JSON.parse(readFileSync(join(root, 'data', 'library.json'), 'utf8'))
    for (const skill of state.skills) writeFileSync(join(root, 'data', 'packages', skill.directory, 'SKILL.md'), 'modified')
    expect(library.configure('alice', 'one', 'disable', 2).skills.find(skill => skill.id === 'one')?.enabled).toBe(false)
    expect(library.configure('alice', 'two', 'remove', 3).skills.find(skill => skill.id === 'two')?.assigned).toBe(false)
    expect(library.snapshot('alice').instruction).toBe('')
  })
  it('rejects invalid references and does not overwrite an existing installation', () => {
    const { source, library } = fixture()
    expect(() => library.publish('../outside', source)).toThrow(/标识/)
    library.publish('careful-review', source)
    expect(() => library.publish('careful-review', source)).toThrow(/已安装/)
  })
  it('detects content changes after installation and preserves corrupt metadata', () => {
    const { root, source, library } = fixture()
    const skill = library.publish('careful-review', source)
    library.configure('alice', skill.id, 'enable', 0)
    const state = JSON.parse(readFileSync(join(root, 'data', 'library.json'), 'utf8'))
    writeFileSync(join(root, 'data', 'packages', state.skills[0].directory, 'SKILL.md'), '被篡改')
    expect(() => library.snapshot('alice')).toThrow(/变化|校验/)
    writeFileSync(join(root, 'data', 'library.json'), 'broken')
    expect(() => new SkillLibrary(join(root, 'data')).list('alice')).toThrow(/技能库/)
    expect(readFileSync(join(root, 'data', 'library.json'), 'utf8')).toBe('broken')
  })
  it('removes missing package metadata so the skill can be reinstalled', () => {
    const { root, source, library } = fixture()
    library.publish('one', source)
    const state = JSON.parse(readFileSync(join(root, 'data', 'library.json'), 'utf8'))
    rmSync(join(root, 'data', 'packages', state.skills[0].directory), { recursive: true })
    library.uninstall('one')
    expect(library.publish('one', source).id).toBe('one')
  })
  it('does not publish files or assignments when durable writes fail', () => {
    const { root, source, library } = fixture()
    const lock = join(root, 'data', 'library.json.tmp')
    mkdirSync(lock)
    expect(() => library.publish('one', source)).toThrow()
    expect(library.list('alice').skills).toEqual([])
    rmSync(lock, { recursive: true })
    library.publish('one', source)
    mkdirSync(lock)
    expect(() => library.configure('alice', 'one', 'enable', 0)).toThrow()
    expect(library.list('alice').revision).toBe(0)
    expect(library.snapshot('alice').entries).toEqual([])
  })
})
